### ISSUE TITLE
Mips, powerpc

### ISSUE THREAD

**Issue by JernejL** [BeRo1985/pasmp#10]
Maybe this can be of some use for mips and powerpc lock-free implementations: 
 
https://www.cl.cam.ac.uk/techreports/UCAM-CL-TR-579.pdf
 
> I used the techniques described in this section to implement a portable library of
lock-free abstractions and structures for Alpha, Intel IA-32, Intel IA-64, MIPS,
PowerPC and SPARC processor families.

**Comment by BeRo1985** [comment]
The MIPS architecture is commerically sadly almost dead, even Google have removed MIPS support at Android last year in their NDK now, and even if most of the consumer routers still have a MIPS-based SoC, but that will also decrease over time soon, I guess.

And at PowerPC I'm seeing a similar situation in the long run, no matter if there are still PowerPC-based Amiga clones or not, and no matter if OpenPOWER will still exist or not, and in the supercomputer area the x86 architecture  has already won for a long time (and ARM is also slowly catching up at the moment in the supercomputer area), etc. 

In my opinion, only the following three CPU architectures will be important in the future: x86 (x86-32/i386/i686 and x86-64/AMD64), ARM (including AArch64) and maybe RISC-V.

**Comment by JernejL** [comment]
I completely agree with you, that those platforms are dead, especially now that all the major consoles are x86_64 based. It's just that i came across the document, and thought you might find it useful :)
