### ISSUE TITLE
[Not an issue] PasMP just helped FPC get the top Binary Trees score on BenchmarkGames!

### ISSUE THREAD

**Issue by Akira13641** [BeRo1985/pasmp#11]
[Just thought I'd link you to this.](https://benchmarksgame-team.pages.debian.net/benchmarksgame/performance/binarytrees.html)

**Comment by BeRo1985** [comment]
Hm, `with TData(Data^)[FromIndex] do begin`  should be `for Index := FromIndex To ToIndex do with TData(Data^)[Index] do begin` :-)

**Comment by Akira13641** [comment]
That was one thing that has confused me actually... when I've used `WriteLn` to examine the values of `FromIndex` and `ToIndex` before, it seems like they are _always_ the exact same number, meaning the for loop would not do anything.  
  
How does that work, exactly?

**Comment by BeRo1985** [comment]
ParallelFor spilts the whole range in multiple FromIndex..ToIndex sub-ranges parallel-recursively, so you must do `for CurrentWorkIndex:=FromIndex to ToIndex do begin ... end;`  in any case, even when FromIndex is (most) always the same value like ToIndex on your own system, but it can different on other systems (for example for higher CPU core counts) or even on different system loads on your current system. Otherwise the benchmark implementation is not valid.

**Comment by Akira13641** [comment]
Would this be the correct way to write it, then:

    class procedure TNode.DoTrees(const Job: PPasMPJob;
                                  const ThreadIndex: TPasMPInt32;
                                  const Data: Pointer;
                                  const FromIndex, ToIndex: TPasMPNativeInt);
    var
      Index: TPasMPNativeInt;
      Inner: TPasMPInt32;
      IPool: TMemPool;
    begin
      for Index := FromIndex to ToIndex do with TData(Data^)[Index] do begin
        Check := 0;
        Depth := MinDepth + FromIndex * 2;
        Iterations := 1 shl (MaxDepth - FromIndex * 2);
        IPool := TMemPool.Create(SizeOf(TNode));
        for Inner := 1 to Iterations do begin
          Check += CheckNode(MakeTree(Depth, IPool));
          IPool.Clear();
        end;
        IPool.Free()
      end;
    end;

**Comment by BeRo1985** [comment]
Rather

```
class procedure TNode.DoTrees(const Job: PPasMPJob;
                              const ThreadIndex: TPasMPInt32;
                              const Data: Pointer;
                              const FromIndex, ToIndex: TPasMPNativeInt);
var
  Index: TPasMPNativeInt;
  Inner: TPasMPInt32;
  IPool: TMemPool;
begin
  for Index := FromIndex to ToIndex do with TData(Data^)[Index] do begin
    Check := 0;
    Depth := MinDepth + Index * 2;
    Iterations := 1 shl (MaxDepth - Index * 2);
    IPool := TMemPool.Create(SizeOf(TNode));
    for Inner := 1 to Iterations do begin
      Check += CheckNode(MakeTree(Depth, IPool));
      IPool.Clear();
    end;
  end;
  IPool.Free();
end;
```
where all `FromIndex` are replaced with `Index`, and not just the first appearance of `FromIndex`.

**Comment by BeRo1985** [comment]
and play with the `Granularity` parameter of `ParallelFor`, this is the smallest minimum value, how small a subdivided subrange can be as a minimum size.

**Comment by Akira13641** [comment]
Ok, I'll try a version with that. The benchmark did seem to give inconsistent results, so maybe that's why.

One other question: do you think it would be faster to do:

    with TPasMP.Create() do begin
      Invoke(ParallelFor(@Data, 0, High(Data), @TNode.DoTrees));
      Free();
    end;  
  
than it is to create the global instance?

**Comment by BeRo1985** [comment]
Just use TPasMP.GetGlobalInstance in the most normal cases. Individal TPasMP instances are only for special cases necessary, for example when the root thread of a TPasMP instance is/should not the main thread of the whole process instance, and so on.

**Comment by BeRo1985** [comment]
And please notify me, when it is also updated on `https://benchmarksgame-team.pages.debian.net/benchmarksgame/performance/binarytrees.html`

**Comment by Akira13641** [comment]
It just went back up to the top again (both of the existing "incorrect" versions I've submitted so far.)  
  
I will let you know when the new "correct" version has gone up though, certainly. Thanks again for the great library!
