### ISSUE TITLE
PasMP doesn't work in Parallel Mode on Linux

### ISSUE THREAD

**Issue by Xor-el** [BeRo1985/pasmp#12]
Hi.
First of all, I must appreciate the splendid work you do on PasMP.

While trying to integrate PasMP into a codebase of mine to achieve parallelism, I figured out that I didn't get the speed improvement I expected on Linux (Do note that Windows works fine).
After some investigations, I figured out that PasMP doesn't run the tasks in Parallel unfortunately on Linux.
Do note that my Linux Box has 4 CPU's so this is not a case of having just one core.

Attached below is a Demo that replicates this.
you can easily notice that on Linux, the parallel mode completes the task at the same time with the serial mode while on Windows, the Parallel mode is way faster.
I use FPC 3.0.4 for development.
[PasMPBug.zip](https://github.com/BeRo1985/pasmp/files/3871031/PasMPBug.zip)

**Comment by BeRo1985** [comment]
Try to undefine  PasMPUseWakeUpConditionVariable in PasMP.pas at the line with `{$define PasMPUseWakeUpConditionVariable}` for use normal events instead condition variables for to wake up the worker threads then. 

And so by the way, Linux (even between different kernel versions and between the current for each active task scheduling policies) and Windows (even between different Windows versions) have very different task scheduling behaviors. And condition variables can have different spurious wakeups and spurious non-wakeups behaviors by condition-variable-concept-design, so that is, it's more for permanent continuous workflow (like Games, Multimedia applications, etc.), and less for oneshot workflow (like your example).

**Comment by Xor-el** [comment]
Thanks for your response.
Unfortunately doing what you said yielded no positive results.
Same issue.

**Comment by Xor-el** [comment]
Also please do note that my example is a stripped down version to reproduce the bug.
My real code does much more real heavy work.

**Comment by BeRo1985** [comment]
At me, I've the near same results under Linux and under Windows with FreePascal 3.1.1 and 3.3.1, see screenshots and my fixed example project (since you've forgot the `for Index := FromIndex to ToIndex do` loop inside DoWork

![result](https://user-images.githubusercontent.com/428863/69354442-6484e680-0c80-11ea-9281-6747aaa86241.png)


[bla.pas.txt](https://github.com/BeRo1985/pasmp/files/3875633/bla.pas.txt)

So try a newer development FPC version 🙂

**Comment by Xor-el** [comment]
unfortunately, running your code on my box yields the same timeline for both parallel and serial.
something weird is really happening.
unfortunately, I don't have a newer FPC version installed in my Linux Box at the moment.

![screenprint](https://user-images.githubusercontent.com/12124088/69359598-2d670300-0c89-11ea-8c01-5007ac301d3f.png)

**Comment by Xor-el** [comment]
running the your code on my Windows box using FPC 3.0.4 yields the expected results like mine.
Something is definitely wrong on Linux. 

Also is there any need for the **Index** loop you added because from my debugging and logging, **FromIndex** and **ToIndex** holds the same values at all times.
i.e if **FromIndex** is 4 **ToIndex** will also be 4 and so on.

**Comment by Xor-el** [comment]
Update
So I adapted the code for MTProcs and it worked as expected in both my Linux and Windows boxes. 😐😐

**Comment by BeRo1985** [comment]
I've double-checked also now on my various linux-based notebooks, desktops, dedicated servers and virtual servers (all with Debian 8 (fpc 3.0.0), Debian 9 (fpc 3.0.4) or ArchLinux (fpc 3.3.1)), but I can not reproduce your issue on these machines. So there's something wrong with your Linux kernel so the wake-up events and wake-up condition variable pulses are being swallowed for the until-the-wakeup-sleeping worker threads.

**Comment by BeRo1985** [comment]
And try to add `GlobalPasMPSleepingOnIdle:=false;` before ` TPasMP.CreateGlobalInstance;`  for debugging purposes, for to check, if it works then (but with higher CPU load).

**Comment by Xor-el** [comment]
> 
> 
> And try to add `GlobalPasMPSleepingOnIdle:=false;` before ` TPasMP.CreateGlobalInstance;` for debugging purposes, for to check, if it works then (but with higher CPU load).

unfortunately, the same issues.
I also tried the code on my Ubuntu 16.04, same issues.

![ubuntu](https://user-images.githubusercontent.com/12124088/69365259-37423380-0c94-11ea-9cea-20b5e532b6d5.png)

any other suggestions?

**Comment by Xor-el** [comment]
Kernel versions for my tested Linux boxes are

Ubuntu 16.04 x64 kernel version: 4.4.0-116-generic
Linux Mint 19.2 x64 kernel version: 4.15.0-66-generic

**Comment by BeRo1985** [comment]
Can you give me the complete output of `cat /proc/cpuinfo` and a screenshot of `htop` ?

**Comment by Xor-el** [comment]
> cat /proc/cpuinfo

output of `cat /proc/cpuinfo`
```

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
stepping	: 9
microcode	: 0xb4
cpu MHz		: 2904.001
cache size	: 4096 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid mpx rdseed adx smap clflushopt xsaveopt xsavec xsaves arat md_clear flush_l1d arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
bogomips	: 5808.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 43 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
stepping	: 9
microcode	: 0xb4
cpu MHz		: 2904.001
cache size	: 4096 KB
physical id	: 0
siblings	: 2
core id		: 1
cpu cores	: 2
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid mpx rdseed adx smap clflushopt xsaveopt xsavec xsaves arat md_clear flush_l1d arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
bogomips	: 5808.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 43 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
stepping	: 9
microcode	: 0xb4
cpu MHz		: 2904.001
cache size	: 4096 KB
physical id	: 1
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid mpx rdseed adx smap clflushopt xsaveopt xsavec xsaves arat md_clear flush_l1d arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
bogomips	: 5808.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 43 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
stepping	: 9
microcode	: 0xb4
cpu MHz		: 2904.001
cache size	: 4096 KB
physical id	: 1
siblings	: 2
core id		: 1
cpu cores	: 2
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid mpx rdseed adx smap clflushopt xsaveopt xsavec xsaves arat md_clear flush_l1d arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
bogomips	: 5808.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 43 bits physical, 48 bits virtual
power management:

```
output of htop

![mint](https://user-images.githubusercontent.com/12124088/69366676-221ad400-0c97-11ea-98a4-2e1655970532.png)

**Comment by BeRo1985** [comment]
Hm okay, real 4 CPU threads. Can you check what TPasMP.GetCountOfHardwareThreads is returning on your machines? I'm guessing in moment, that TPasMP.GetCountOfHardwareThreads does probably detect the wrong count of CPU Threads at you.

**Comment by Xor-el** [comment]
> 
> 
> Hm okay, real 4 CPU threads. Can you check what TPasMP.GetCountOfHardwareThreads is returning on your machines? I'm guessing in moment, that TPasMP.GetCountOfHardwareThreads does probably detect the wrong count of CPU Threads at you.

you are right.

![hardwarecount](https://user-images.githubusercontent.com/12124088/69368326-37453200-0c9a-11ea-9ceb-3545ad3c1e80.png)

**Comment by BeRo1985** [comment]
try to modify this function first to

```pascal
class function TPasMP.GetCountOfHardwareThreads(var AvailableCPUCores:TPasMPAvailableCPUCores):TPasMPInt32;
var i:TPasMPInt32;
begin
 result:=4; // >= hardcoded value testwise 
 SetLength(AvailableCPUCores,result);
 for i:=0 to result-1 do begin
  AvailableCPUCores[i]:=i;
 end;
end;
````

and then try change it to
 
```pascal
class function TPasMP.GetCountOfHardwareThreads(var AvailableCPUCores:TPasMPAvailableCPUCores):TPasMPInt32;
var mib:array[0..1] of cint;
    len:cint;
    t:cint;
    i:TPasMPInt32;
begin
 mib[0]:=CTL_HW;
 mib[1]:=HW_AVAILCPU;
 len:=SizeOf(t);
 fpsysctl(PAnsiChar(@mib),2,@t,@len,nil,0);
 if t<1 then begin
  mib[1]:=HW_NCPU;
  fpsysctl(PAnsiChar(@mib),2,@t,@len,nil,0);
  if t<1 then begin
   t:=1;
  end;
 end;
 result:=t;
 SetLength(AvailableCPUCores,result);
 for i:=0 to result-1 do begin
  AvailableCPUCores[i]:=i;
 end;
end;           
````

**Comment by BeRo1985** [comment]
And try the now updated PasMP.pas from the repo also please :)

**Comment by Xor-el** [comment]
> 
> 
> And try the now updated PasMP.pas from the repo also please :)

your updated code works ok now albeit slower.

using this function below

```
class function TPasMP.GetCountOfHardwareThreads(var AvailableCPUCores:TPasMPAvailableCPUCores):TPasMPInt32;
var i:TPasMPInt32;
begin
 result:=4; // >= hardcoded value testwise 
 SetLength(AvailableCPUCores,result);
 for i:=0 to result-1 do begin
  AvailableCPUCores[i]:=i;
 end;
end;
```
![1](https://user-images.githubusercontent.com/12124088/69371257-c7d24100-0c9f-11ea-9419-892f53fcf66e.png)


using your updated code from repo

![2](https://user-images.githubusercontent.com/12124088/69371280-d7ea2080-0c9f-11ea-952f-e8b1d5e83984.png)

**Comment by Xor-el** [comment]
> And try the now updated PasMP.pas from the repo also please :)

So I noticed something weird now.

if I use the code below which is same as that you updated

``` pascal
begin
 result:=sysconf(_SC_NPROCESSORS_CONF);
 SetLength(AvailableCPUCores,result);
 sched_getaffinity(GetProcessID,SizeOf(CPUSet),@CPUSet);
 j:=0;
 for i:=0 to 63 do begin
  if (CPUSet and (TPasMPInt64(1) shl i))<>0 then begin
   AvailableCPUCores[j]:=i;
   inc(j);
   if j>=result then begin
    break;
   end;
  end;
 end;
 if result>j then begin
  result:=j;
  SetLength(AvailableCPUCores,result);
 end;
end;
```

I get this

![1a](https://user-images.githubusercontent.com/12124088/69372263-a40ffa80-0ca1-11ea-8648-e1a916167855.png)

but if I modify your code to this below

``` pascal
begin
 result:=sysconf(_SC_NPROCESSORS_CONF);
 SetLength(AvailableCPUCores,result);
 sched_getaffinity(GetProcessID,SizeOf(CPUSet),@CPUSet);
 j:=0;
 for i:=0 to 127 do begin   // <====== Max Index is the difference here
  if (CPUSet and (TPasMPInt64(1) shl i))<>0 then begin
   AvailableCPUCores[j]:=i;
   inc(j);
   if j>=result then begin
    break;
   end;
  end;
 end;
 if result>j then begin
  result:=j;
  SetLength(AvailableCPUCores,result);
 end;
end;
```

I get this

![1b](https://user-images.githubusercontent.com/12124088/69372348-d588c600-0ca1-11ea-921e-903aae580707.png)


what do you think?

**Comment by BeRo1985** [comment]
0..63 is right, because a Int64 can hold only 64 bits, and not 128 bits at 0..127, so that it would wrap around at the x86 cpu ISA after the 64th bit. So here would be following code twice executed then:

```pascal
   AvailableCPUCores[j]:=i;
   inc(j);
```

for double so much worker threads than as real native CPU threads available then.

**Comment by Xor-el** [comment]
> 
> 
> 0..63 is right, because a Int64 can hold only 64 bits, and not 128 bits at 0..127, so that it would wrap around at the x86 cpu ISA after the 64th bit. So here would be following code twice executed then:
> 
> ```pascal
>    AvailableCPUCores[j]:=i;
>    inc(j);
> ```
> 
> for double so much worker threads than as real native CPU threads available then.

unfortunately, for 0..63, the parallel mode takes the same time as the serial version meaning the problem is unfortunately not solved.

**Comment by BeRo1985** [comment]
Can you give the value of the CPUSet variable (per a `writeln(UInt64(CPUSet));` )? For to see which bits are set at your machine.

**Comment by Xor-el** [comment]
> writeln(UInt64(CPUSet));

`CPUSet: 139768131018840`

**Comment by Xor-el** [comment]
I am seeing more strange things.
The first output is when I added a writeln to print the CPUSet variable.
the second output is when I commented out the writeln 

I feel the OS needs something like a stall for it to function properly.

![stall](https://user-images.githubusercontent.com/12124088/69378218-3918f080-0cae-11ea-8730-55fa5bb2de89.png)

**Comment by BeRo1985** [comment]
Try to set `CPUSet:=0;` before the `sched_getaffinity` call and  then writeln CPUSet again, please. For to check, if sched_getaffinity on your Ubuntu system touches the CPUSet variable at after all or not. Because it looks for a uninitiliaized int64 value otherwise.

**Comment by Xor-el** [comment]
> CPUSet:=0;

you are right, `sched_getaffinity` does not initialize `CPUSet` on my system.

![cpu](https://user-images.githubusercontent.com/12124088/69378922-aaa56e80-0caf-11ea-9113-87ac84ab9cc7.png)

**Comment by BeRo1985** [comment]
Then try the again updated PasMP.pas where `if sched_getaffinity(GetProcessID,SizeOf(CPUSet),@CPUSet)=0 then ...` will be checked also now.

**Comment by Xor-el** [comment]
`sched_getaffinity ` returned `-1` meaning it failed.

![uu](https://user-images.githubusercontent.com/12124088/69379183-3d460d80-0cb0-11ea-858d-daeafd5a0b4c.png)

**Comment by Xor-el** [comment]
the sick thing here is that `fpgeterrno` FPC's equivalent of Linux `errno` returns `0` which indicates that no error occurred in the program. strange.

![err](https://user-images.githubusercontent.com/12124088/69379826-7fbc1a00-0cb1-11ea-8ca2-fbde9c3bee94.png)

**Comment by BeRo1985** [comment]
Yes, that's why it looks like that in the latest PasMP.pas: 

```pascal
var i,j:TPasMPInt32;
    CPUSet:TPasMPInt64;
begin
 result:=sysconf(_SC_NPROCESSORS_CONF);
 SetLength(AvailableCPUCores,result);
 CPUSet:=0;
 if sched_getaffinity(GetProcessID,SizeOf(CPUSet),@CPUSet)=0 then begin
  j:=0;
  for i:=0 to 63 do begin
   if (CPUSet and (TPasMPInt64(1) shl i))<>0 then begin
    AvailableCPUCores[j]:=i;
    inc(j);
    if j>=result then begin
     break;
    end;
   end;
  end;
  if result>j then begin
   result:=j;
   SetLength(AvailableCPUCores,result);
  end;
 end else begin
  for i:=0 to result-1 do begin
   AvailableCPUCores[i]:=i;
  end;
 end;
end;
```

so that when sched_getaffinity fails, then the AvailableCPUCores array will just fill only on basis of the sysconf(_SC_NPROCESSORS_CONF) result value.

**Comment by Xor-el** [comment]
splendid. everything works ok with the latest commit.
Thanks for your time.
it's very much appreciated.
