### ISSUE TITLE
error in ParallelDirectIntroSort

### ISSUE THREAD

**Issue by Imageman** [BeRo1985/pasmp#2]
error in ParallelDirectIntroSort
demo
http://pastebin.com/x9U22C8K

on small N all Ok; On N=10000 error (some values dublicate)

**Comment by Imageman** [comment]
Fixed ParallelDirectIntroSort.
ParallelDirectMergeSort  demo test failed!

**Comment by BeRo1985** [comment]
In your pastebin code I see `GlobalPasMP.Invoke(GlobalPasMP.ParallelDirectMergeSort(@DataArray[0],0,N-1,SizeOf(longint),CompareInteger,16,8)); // <= Invoke = Run+Wait+Release into a single call` which must be also `GlobalPasMP.Invoke(GlobalPasMP.ParallelDirectMergeSort(@DataArray[0],0,N-1,SizeOf(TSimpleVal),CompareSimpleVal,16,8));` then it works, at least at me, see: [https://youtu.be/VlknV2WYOTU](https://youtu.be/VlknV2WYOTU)

**Comment by Imageman** [comment]
Yes!
Sorry, this is my problem :-(
All 'Ok'. Thanks.
