### ISSUE TITLE
inconsistent newlines

### ISSUE THREAD

**Issue by jBitHub** [BeRo1985/pasmp#8]
PasMP.pas has inconsistent newlines   [LF]      [CR][LF]

Line [3310]
 ldaxp x5,x1,[x0][LF]
 cmp x5,x3[LF]
 bne Fail[LF]
 cmp x1,x4[LF]
 bne Fail[LF]
 stlxp w7,x6,x2,[x0][LF]
 cbnz w7,Loop[LF]
Fail:[LF]
 mov x0,x5[LF]

**Comment by BeRo1985** [comment]
Fixed. However, modern editors should have no problems with that. (And no, the editor of the now really old Delphi 7 IDE is not modern in this context :-) )

**Comment by jBitHub** [comment]
thx 
Delphi 7 have no problems
SVN can't check in

**Comment by BeRo1985** [comment]
Hm, SVN had never problems with mixed LF/CRLF newlines at me (neither under Linux nor under Windows nor under MacOS(X) ). I'm using GitHub mostly only with SVN with the GitHub-own SVN<=>Git gateway and also I'm running a own SVN server instance on my private dedicated rootserver.
